# Generated by Django 3.0.8 on 2020-07-22 21:19

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditoryAttendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('absolute_attendance_name', models.CharField(blank=True, max_length=200, unique=True)),
                ('grade', models.CharField(choices=[('+', 'Присутствует'), ('нб.', 'Отсутствует'), ('нб.(ув.)', 'Отсутствует (по уважительной причине)'), ('?', 'Не отмечено')], default=('?', 'Не отмечено'), max_length=50, verbose_name='Оценка посещаемости')),
            ],
            options={
                'verbose_name': 'оценка посещаемости занятия',
                'verbose_name_plural': 'оценки посещаемости занятия',
            },
        ),
        migrations.CreateModel(
            name='AuditoryLessons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Дата занятия')),
                ('lessons_number', models.IntegerField(blank=True, verbose_name='Номер занятия')),
                ('theme', models.TextField(blank=True, max_length=200, verbose_name='Тема занятия')),
                ('type_employment', models.CharField(choices=[('Лек.', 'Лекция'), ('ЛР', 'Лабораторная работа'), ('ПР', 'Практическая работа')], default=('Лек.', 'Лекция'), max_length=50, verbose_name='Вид занятия')),
            ],
            options={
                'verbose_name': 'занятие',
                'verbose_name_plural': 'занятия',
            },
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0, verbose_name='Номер')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('type', models.CharField(choices=[('Текущая аттестация', 'Текущая аттестация'), ('Промежуточная аттестация', 'Промежуточная аттестация')], default=('Текущая аттестация', 'Текущая аттестация'), max_length=50, verbose_name='Вид')),
            ],
            options={
                'verbose_name': 'аттестация',
                'verbose_name_plural': 'аттестации',
            },
        ),
        migrations.CreateModel(
            name='Certification_control_work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField(default=0, verbose_name='Вес работы')),
            ],
            options={
                'verbose_name': 'работа с аттестацией',
                'verbose_name_plural': 'работы с аттестацией',
            },
        ),
        migrations.CreateModel(
            name='Certification_control_work_grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField(default=0, verbose_name='Оценка за работу')),
            ],
            options={
                'verbose_name': 'оценка работы с аттестацией',
                'verbose_name_plural': 'оценки работы с аттестацией',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=500, verbose_name='Сообщение')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата сообщения')),
                ('is_readed', models.BooleanField(default=False, verbose_name='Прочитано')),
            ],
            options={
                'verbose_name': 'комментарий',
                'verbose_name_plural': 'комментарии',
                'ordering': ['pub_date'],
            },
        ),
        migrations.CreateModel(
            name='Control_work_grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField(blank=True, null=True, verbose_name='Оценка за работу')),
                ('status', models.CharField(choices=[('Не сдавалась', 'Не сдавалась'), ('Сдавалась', 'Сдавалась'), ('Зачет', 'Зачет')], default=('Не сдавалась', 'Не сдавалась'), max_length=50, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'оценка контроля студентов',
                'verbose_name_plural': 'оценки контроля студентов',
            },
        ),
        migrations.CreateModel(
            name='ControlCriterion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criterion_number', models.IntegerField(blank=True, default=0, verbose_name='Номер критерия')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('weight', models.IntegerField(default=0, verbose_name='Вес критерия')),
                ('is_subcriterion', models.BooleanField(default=False, verbose_name='Это подкритерий')),
            ],
            options={
                'verbose_name': 'критерий контроля',
                'verbose_name_plural': 'критерии контроля',
            },
        ),
        migrations.CreateModel(
            name='ControlScale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimension', models.IntegerField(verbose_name='Размерность')),
            ],
            options={
                'verbose_name': 'шкала контроля',
                'verbose_name_plural': 'шкалы контроля',
            },
        ),
        migrations.CreateModel(
            name='ControlScaleTranslate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perfectly', models.IntegerField(default=100, verbose_name='Отлично')),
                ('good', models.IntegerField(default=80, verbose_name='Хорошо')),
                ('satisfactorily', models.IntegerField(default=60, verbose_name='Удовлетворительно')),
                ('badly', models.IntegerField(default=40, verbose_name='Неудовлетворительно')),
            ],
            options={
                'verbose_name': 'перевод шкалы контроля',
                'verbose_name_plural': 'переводы шкалы контроля',
            },
        ),
        migrations.CreateModel(
            name='ControlType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('distance_work_check', models.BooleanField(default=False, verbose_name='Дистанционная проверка работ')),
                ('have_general_criterions', models.BooleanField(default=False, verbose_name='Имеет ли общие критерии для всего вида контроля')),
            ],
            options={
                'verbose_name': 'вид контроля',
                'verbose_name_plural': 'виды контроля',
            },
        ),
        migrations.CreateModel(
            name='ControlWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_number', models.IntegerField(blank=True, default=0, verbose_name='Номер работы')),
                ('name', models.TextField(max_length=200, verbose_name='Название')),
                ('weight', models.IntegerField(default=0, verbose_name='Вес работы')),
            ],
            options={
                'verbose_name': 'работа',
                'verbose_name_plural': 'работы',
            },
        ),
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'дисциплина',
                'verbose_name_plural': 'дисциплины',
            },
        ),
        migrations.CreateModel(
            name='EducationalEstablishment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50, unique=True, verbose_name='Полное название')),
                ('abbreviation', models.CharField(max_length=50, unique=True, verbose_name='Аббревиатура')),
            ],
            options={
                'verbose_name': 'образовательное учреждение',
                'verbose_name_plural': 'образовательные учреждения',
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='django.core.files.storage.FileSystemStorage', verbose_name='файл')),
            ],
            options={
                'verbose_name': 'файл',
                'verbose_name_plural': 'файлы',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('absolute_journal_name', models.CharField(blank=True, max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'журнал',
                'verbose_name_plural': 'журналы',
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, unique=True, verbose_name='Название')),
                ('date_start', models.DateField(verbose_name='Дата начала')),
                ('date_end', models.DateField(verbose_name='Дата окончания')),
            ],
            options={
                'verbose_name': 'семестр',
                'verbose_name_plural': 'семестры',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_in_group', models.IntegerField(blank=True, verbose_name='Номер варианта в группе')),
            ],
            options={
                'verbose_name': 'студент',
                'verbose_name_plural': 'студенты',
            },
        ),
        migrations.CreateModel(
            name='StudentGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название')),
                ('year_start_studing', models.IntegerField(verbose_name='Год начала обучения')),
                ('year_end_studing', models.IntegerField(verbose_name='Год окончания обучения')),
                ('specialty', models.CharField(blank=True, max_length=50, verbose_name='Специальность')),
            ],
            options={
                'verbose_name': 'группа',
                'verbose_name_plural': 'группы',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'преподаватель',
                'verbose_name_plural': 'преподаватели',
            },
        ),
        migrations.CreateModel(
            name='TeleWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_date', models.DateTimeField(default=datetime.datetime(2020, 7, 22, 21, 19, 34, 779215), verbose_name='Время сдачи на проверку')),
                ('check_date', models.DateTimeField(blank=True, null=True, verbose_name='Время проверки')),
                ('is_checked', models.BooleanField(default=False, verbose_name='Проверена ли работа')),
                ('grade', models.IntegerField(default=0, verbose_name='Оценка за работу')),
                ('additional_comment', models.TextField(blank=True, max_length=500, null=True, verbose_name='Дополнительное примечание')),
                ('additional_comment_student', models.TextField(blank=True, max_length=500, null=True, verbose_name='Дополнительное примечание студента')),
                ('control_grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tele_works', to='mainapp.Control_work_grade', verbose_name='Оценка, привязанная к проверке')),
                ('files', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tele_works', to='mainapp.File', verbose_name='Файл')),
            ],
            options={
                'verbose_name': 'работа на проверку',
                'verbose_name_plural': 'работы на проверку',
            },
        ),
        migrations.CreateModel(
            name='TeleWorkCriterions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField(default=0, verbose_name='Оценка за работу')),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tele_work_criterions', to='mainapp.ControlCriterion', verbose_name='Критерий')),
                ('telework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tele_work_criterions', to='mainapp.TeleWork', verbose_name='Работа на проверку')),
            ],
            options={
                'verbose_name': 'критерий работы на проверку',
                'verbose_name_plural': 'критерии работы на проверку',
            },
        ),
        migrations.CreateModel(
            name='TeleWorkCriterionsCommentStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=500, verbose_name='Коммент')),
                ('is_checked', models.BooleanField(default=False, verbose_name='Просмотрен ли комментарий')),
                ('teleworkcriterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tele_work_criterion_comment_student', to='mainapp.TeleWorkCriterions', verbose_name='Критерий работы на проверку')),
            ],
            options={
                'verbose_name': 'комментарий критерия работы на проверку от студента',
                'verbose_name_plural': 'комментарии критерия работы на проверку от студентов',
            },
        ),
        migrations.CreateModel(
            name='TeleWorkCriterionsComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=500, verbose_name='Коммент')),
                ('comment_type', models.TextField(max_length=100, verbose_name='Типовое замечание')),
                ('is_checked', models.BooleanField(default=False, verbose_name='Просмотрен ли комментарий')),
                ('teleworkcriterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tele_work_criterion_comment', to='mainapp.TeleWorkCriterions', verbose_name='Критерий работы на проверку')),
            ],
            options={
                'verbose_name': 'комментарий критерия работы на проверку',
                'verbose_name_plural': 'комментарии критерия работы на проверку',
            },
        ),
    ]
