# Generated by Django 3.0.8 on 2020-08-05 13:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20200722_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='control_work_grade',
            name='status',
            field=models.CharField(choices=[('Не отправлялась на проверку', 'Не отправлялась на проверку'), ('Отправлена на проверку {N}-й раз', 'Отправлена на проверку {N}-й раз'), ('Зачтена', 'Зачтена'), ('Проверена {N}-й раз (есть замечания)', 'Проверена {N}-й раз (есть замечания)')], default=('Не отправлялась на проверку', 'Не отправлялась на проверку'), max_length=100, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teachergroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teachergroup', to='mainapp.StudentGroup', verbose_name='Курируемая группа'),
        ),
        migrations.AlterField(
            model_name='telework',
            name='delivery_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 5, 13, 32, 57, 77344), verbose_name='Время сдачи на проверку'),
        ),
    ]
